src/CMon/ViewModels/Device/AddDeviceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CMon.ViewModels.Device
{
	public class AddDeviceViewModel
	{
		[Required]
		[StringLength(64)]
		[Display(Name = "Name")]
		public string Name { get; set; }

		[Required]
		[StringLength(15, MinimumLength = 15)]
		[Display(Name = "IMEI")]
		public string Imei { get; set; }

		[Required]
		[StringLength(100)]
		[Display(Name = "Username")]
		public string Username { get; set; }

		[Required]
		[StringLength(100)]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		public string Password { get; set; }
	}
}

src/CMon/ViewModels/Device/DeviceViewModel.cs
using System.Collections.Generic;

namespace CMon.ViewModels.Device
{
	public class DeviceListViewModel
	{
		public IList<DeviceViewModel> Items { get; set; }
	}
	
	public class DevicePageViewModel
	{
		public long? Id { get; set; }

		public IList<DeviceViewModel> Devices { get; set; }

		public DateRange[][] QuickRanges { get; set; }
	}
	
	public class DeviceViewModel
	{
		public string Url { get; set; }

		public long Id { get; set; }

		public string Name { get; set; }

		public string Imei { get; set; }
	}
	
	public class BlockViewModel
	{
		public string Type { get; set; }

		public string Name { get; set; }

		public short InputNo { get; set; }
	}
	
	public class DateRange
	{
		public string Name { get; set; }

		public string From { get; set; }

		public string To { get; set; }
	}
}

src/CMon/Controllers/Apis/DeviceController.cs
using System.Threading;
using System.Threading.Tasks;
using CMon.Requests;
using CMon.Services;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMon.Controllers.Apis
{
	[Authorize]
	[Route("api/[controller]")]
	public class DeviceController : Controller
	{
		private readonly IIdentityProvider _identityProvider;
		private readonly IBackgroundJob _job;
		private readonly IMediator _mediator;

		public DeviceController(IIdentityProvider identityProvider, IBackgroundJob job, IMediator mediator)
		{
			_identityProvider = identityProvider;
			_job = job;
			_mediator = mediator;
		}

		[HttpPost("blocks")]
		public async Task<GetDeviceBlocks.Result> GetBlocks(long deviceId)
		{
			return await _mediator.Send(new GetDeviceBlocks
			{
				UserName = _identityProvider.GetUserName(),
				DeviceId = deviceId
			});
		}

		[HttpGet("values")]
		public async Task<GetDeviceInputs.Result> GetValues(long deviceId, string from, string to)
		{
			return await _mediator.Send(new GetDeviceInputs
			{
				UserName = _identityProvider.GetUserName(),
				DeviceId = deviceId,
				BeginDate = from,
				EndDate = to
			});
		}

		[HttpPost("events")]
		public async Task<GetDeviceEvents.Result> GetEvents(long deviceId, string from, string to)
		{
			return await _mediator.Send(new GetDeviceEvents
			{
				UserName = _identityProvider.GetUserName(),
				DeviceId = deviceId,
				BeginDate = from,
				EndDate = to
			});
		}

		[HttpPost("refresh")]
		public void Refresh(long deviceId)
		{
			_job.Enqueue<IMediator>(x => x.Send(new RefreshDevice
			{
				DeviceId = deviceId,
				UserName = _identityProvider.GetUserName()
			}, CancellationToken.None));
		}

		[HttpPost("status")]
		public async Task<string> GetStatus(long deviceId)
		{
			return await _mediator.Send(new GetDeviceStatus
			{
				DeviceId = deviceId
				// UserName = _identityProvider.GetUserName()
			});
		}
	}
}

src/CMon/Views/Device/Add.cshtml
@model CMon.ViewModels.Device.AddDeviceViewModel

@{
	ViewData["Title"] = "Add Device";
}

<div class="modal-content modal-lg center-block">
	<div class="modal-header">
		<h4 class="modal-title">@ViewData["Title"]</h4>
	</div>
	<div class="modal-body">

		<form asp-controller="Device" asp-action="Add" method="post" class="form-horizontal">
			
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<div class="form-group required">
				<label asp-for="Name" class="col-md-2 control-label"></label>
				<div class="col-md-10">
					<input asp-for="Name" class="form-control" aria-describedby="Name-helpBlock" autofocus />
					<span asp-validation-for="Name" class="text-danger"></span>
					<span id="Name-helpBlock" class="help-block">Наименование контроллера для отображения в панели управления, например &laquo;Дача&raquo;.</span>
				</div>
			</div>

			<div class="form-group required">
				<label asp-for="Imei" class="col-md-2 control-label"></label>
				<div class="col-md-6">
					<input asp-for="Imei" class="form-control" aria-describedby="Imei-helpBlock" />
					<span asp-validation-for="Imei" class="text-danger"></span>
					<span id="Imei-helpBlock" class="help-block">15-тизначное число, которое можно взять со страницы контроллера <a href="https://ccu.sh/index.cgi" target="_blank">https://ccu.sh/index.cgi</a>.</span>
				</div>
			</div>

			<div class="form-group required">
				<label asp-for="Username" class="col-md-2 control-label"></label>
				<div class="col-md-4">
					<input asp-for="Username" class="form-control" aria-describedby="Username-helpBlock" />
					<span asp-validation-for="Username" class="text-danger"></span>
					<span id="Username-helpBlock" class="help-block">Имя пользователя контроллера.</span>
				</div>

				<label asp-for="Password" class="col-md-2 control-label"></label>
				<div class="col-md-4">
					<input asp-for="Password" class="form-control" aria-describedby="Password-helpBlock" />
					<span asp-validation-for="Password" class="text-danger"></span>
					<span id="Password-helpBlock" class="help-block">Пароль пользователя контроллера.</span>
				</div>
			</div>
			
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<p class="text-danger"><strong>Внимание:</strong> Для начального считывания параметров контроллера (входов, выходов и т.д.) пользователь контроллера должен быть администратором.
						Ручной ввод параметров контроллера (пока?) не предусмотрен.</p>
					<button type="submit" class="btn btn-primary">Add</button>
				</div>
			</div>

		</form>

	</div>
</div>

@section scripts {
	@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/CMon/Views/Device/List.cshtml
@model CMon.ViewModels.Device.DeviceListViewModel

<ul class="device-list list-group">
	@foreach (var item in Model.Items)
	{
		<li class="list-group-item">
			<h4 class="list-group-item-heading">@item.Name</h4>
			<p class="list-group-item-text">@item.Imei</p>

			<button type="button" class="btn btn-default btn-refresh" data-device-id="@item.Id">Обновить</button>
			<a href="@Url.Action("Index", "Device", new { id = item.Id })">Просмотр</a>
			<span class="status"></span>

		</li>
	}
</ul>